globals:
  wp_cluster_path: https://raw.githubusercontent.com/sych74/wordpress-cluster/v2.1.0
  wp_standalone_path: https://raw.githubusercontent.com/sych74/wordpress/v3.0.0
  db_cluster_path: https://raw.githubusercontent.com/jelastic-jps/mysql-cluster/v2.4.1
