jps: https://github.com/ihorstep/wordpress/blob/master/wordpress/manifest.jps
component: wordpress
subfolders:
  - wordpress
stack:
  - nodeType: lemp
    nodeGroup: cp
    optimization: false
    options:
      - ls-addon: false
  - nodeType: llsmp
    nodeGroup: cp
    optimization: false
    options:
      - ls-addon: true

